config/routes.rb
Paintball::Application.routes.draw do

  get "static_pages/home"

  get "static_pages/contact"

  get "static_pages/about"

  get "static_pages/tournaments"

  get "static_pages/current_roster"

  get "static_pages/users"

  get "static_pages/gears"

  resources :tournaments do
    resources :participants
    resources :results
  end

  resources :users do
    get "mark_interested_gear", on: :member #member means you have to give it a user's id
    get "mark_uninterested_gear", on: :member
    resources :gears
  end
  resources :users

  root to: 'static_pages#home'

  resources :tournaments

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :gears, only: [:index, :show]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	respond_to do |format|
  		format.html 
  		format.js 
  	end
  end

  def tournaments
  	@tournaments = Tournament.all
  	respond_to do |format|
  		format.js
  	end
  end

  def users
  	@users = User.all
  	respond_to do |format|
  		format.js
  	end
  end

  def current_roster
  	@users = User.all
    respond_to do |format|
      format.js
     end
  end

  def gears
  	@gears = Gear.all
  	respond_to do |format|
  		format.js
  	end
  end


  def contact
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_current_roster.html.erb
<table class="table table-striped" id="current_player_listing">
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>


  </tr>

<% @users.each do |user| %>
  <% unless user.status == "Alumni" %>
  <tr id="<%= user_id_helper(user) %>">
    <td><%= link_to user.name, user %></td>
    <td><%= user.status %></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<% end %>
<% end %>
</table>

<%= link_to "Back to All Players", static_pages_users_path, id: "players_link", remote: true %>

app/views/static_pages/_g_index.html.erb
<table class="table table-striped" id="gear_listing">
  <tr>
    <th>Name</th>
    <th>Owner</th>
    <th>For Sale</th>
    <th>Cost</th>
    <th></th>
  </tr>

<% User.all.each do |user| %>
<% user.gears.each do |gear| %>
  <tr id="<%= gear_id_helper(gear) %>">
    <td><%= link_to gear.name, gear %></td>
    <td><%= user.name %></td>
    <% if gear.for_sale %>
    <td>Yes</td>
    <td>$<%= gear.cost %></td>
    <% else %>
    <td>No</td>
    <td>N/A</td>
    <% end %>
    <% if can? :destroy, gear %>
    <td><%= link_to 'Destroy', user_gear_path(user, gear), confirm: 'Are you sure?', method: :delete, :class => "btn btn-small btn-danger", remote: true %></td>
    <% end %>
  </tr>
<% end %>
<% end %>
</table>

app/views/static_pages/_modal.html.erb
<div id="myModal" class="modal hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <%= render('sessions/form') %>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>
</div>

app/views/static_pages/_t_index.html.erb
<div class="place">
<table id="tournament_listing" class="table table-striped table-rounded">
  <tr>
    <th>Date</th>
    <th>Location</th>
    <th></th>
    <th></th>
  </tr>

<% Tournament.all.each do |tournament| %>
  <tr id="<%= tournament_id_helper(tournament) %>">
    <td><%= tournament.date %></td>
    <td><%= tournament.location %></td>
    <td><%= link_to 'View Tournament', tournament %></td>
    <% if can? [:destroy, :update], @tournament %>
    <td><%= link_to 'Destroy', tournament, confirm: 'Are you sure?', method: :delete, :class => "btn btn-small btn-danger", remote: true %></td>
    <% end %>
    
    
  </tr>
<% end %>
</table>

<br />
<% if can? :create, Tournament %>
<%= link_to 'New Tournament', new_tournament_path, id: "new_tournament_link", remote: true %>
<% end %>
</div>

app/views/static_pages/_u_index.html.erb
<table class="table table-striped" id="player_listing">
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>


  </tr>

<% @users.each do |user| %>
  <tr id="<%= user_id_helper(user) %>">
    <td><%= link_to user.name, user %></td>
    <td><%= user.status %></td>
    <% if can? [:update, :destroy], user %>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete, :class => "btn btn-small btn-danger", remote: true %></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if can? :create, @user %>
<%= link_to 'New User', new_user_path, id: "new_player_link", remote: true %>
<% end %>
|
<%= link_to 'Current Roster', static_pages_current_roster_path, remote: true %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/current_roster.js.erb
$('#append_me').html("<%= j render('current_roster') %>");

app/views/static_pages/gears.js.erb
$('#append_me').html("<%= j render('g_index') %>");

app/views/static_pages/home.html.erb
<div class="header">
	<h1>Saint Mary's University of Minnesota Paintball Team</h1>
</div>
<br />
<div class="container">
	<body>
	<div class="span3">
		<p><b>HOME OF THE SMU KIDZ</b></p>
	</div>
	<div class="span14 center" id="append_me">
		<div id="place">
			<p>Where the cool kids are</p>
		</div>
	</div>
	<div class="span3">
	<ul class="nav pull-right">
		<li><%= link_to "tournaments", static_pages_tournaments_path, id: "tournies_link", remote: true %></li>
		<li><%= link_to "players", static_pages_users_path, id: "players_link", remote: true %></li>
		<% if can? :read, @gear %>
		<li><%= link_to 'gear', static_pages_gears_path, id: "gear_link", remote: true %>
		<% end %>
	</ul>
</div>

	</body>
</div>
<br />

app/views/static_pages/tournaments.js.erb
$('#append_me').html("<%= j render('t_index') %>");

app/views/static_pages/users.js.erb
$('#append_me').html("<%= j render('u_index') %>");