config/routes.rb
Paintball::Application.routes.draw do

  get "static_pages/home"

  get "static_pages/contact"

  get "static_pages/about"

  get "static_pages/tournaments"

  get "static_pages/current_roster"

  get "static_pages/users"

  get "static_pages/gears"

  resources :tournaments do
    resources :participants
    resources :results
  end

  resources :users do
    get "mark_interested_gear", on: :member #member means you have to give it a user's id
    get "mark_uninterested_gear", on: :member
    resources :gears
  end
  resources :users

  root to: 'static_pages#home'

  resources :tournaments

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :gears, only: [:index, :show]

end

app/models/user.rb
class User < ActiveRecord::Base
  serialize :interested_in,Array
  attr_accessible :email, :is_admin, :name, :password, :status, :password_confirmation, :interested_in
  has_secure_password
  has_many :gears, dependent: :destroy
  has_many :participants, dependent: :destroy
  has_many :users_gears, dependent: :destroy
  
  

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  
  def self.STATUSES
   %w[Freshmen Sophomore Junior Senior Alumni]
  end

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

  def self.admins(admin = true)
  	where("is_admin == ? ", admin)
  end

  def interested(gear)
    puts "****************** #{self.users_gears}"
    self.users_gears.create!(gear_id: gear.id)
    self.save
    puts "****************** #{self.users_gears}"
  end

  def is_interested(gear)
    self.users_gears.each do |ug|
      return true if ug.gear_id == gear.id
    end
    return false
  end
  def uninterested(gear)
    if self.is_interested(gear)
      self.users_gears.find_by_gear_id(gear.id).destroy
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
      format.js
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      sign_in @user
      redirect_to @user
    else
      redirect_to 'edit'
    end

    #respond_to do |format|
      #if @user.update_attributes(params[:user])
        #format.html { redirect_to @user, notice: 'User was successfully updated.' }
        #format.json { head :no_content }
      #else
        #format.html { render action: "edit" }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      #end
    #end
  end

  def mark_interested_gear
      @user = User.find(params[:id])
      @gear = Gear.find(params[:gear_id])
      @user.interested(@gear)

      respond_to do |format|
        format.html { redirect_to @gear }
        format.js
      end
  end

  def mark_uninterested_gear
    @user = User.find(params[:id])
    @gear = Gear.find(params[:gear_id])
    @user.uninterested(@gear)
    
    respond_to do |format|
      format.html { redirect_to @gear }
      format.js
    end
  end

  

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
	def user_id_helper(user)
		"user_#{user.id}"
	end
end

app/views/users/_form.html.erb
<div id="new_player">
<%= form_for(@user, remote: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :is_admin %><br />
    <%= f.check_box :is_admin %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, User.STATUSES, {}, { :prompt => 'Select Place' } %>
  </div>
  <div class="actions">
    <%= f.submit "Create User" %>
  </div>
<% end %>
</div>

app/views/users/_interested.html.erb
<div id="interested">
<p>Interested in this piece of gear?</p><br >
 <%= link_to "Mark Interested", mark_interested_gear_user_path(current_user, gear_id: @gear.id), :class => "btn btn-large btn-primary", remote: true %>
</div>

app/views/users/_player.html.erb
<tr id="<%= user_id_helper(@user) %>">
    <td><%= link_to @user.name, @user %></td>
    <td><%= @user.status %></td>
    <td><%= link_to 'Destroy', @user, confirm: 'Are you sure?', method: :delete, :class => "btn btn-small btn-danger", remote: true %></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>

app/views/users/_uninterested.html.erb
<div id="uninterested">
<p>You're already interested</p><br >
  <%= link_to "Not Interested Anymore", mark_uninterested_gear_user_path(current_user, gear_id: @gear.id), :class => "btn btn-large btn-danger", remote: true %>
</div>

app/views/users/create.js.erb
$('#new_player').remove();
$('#new_player_link').show();
$('#tournies_link').show();
$('#players_link').show();
$('#gear_link').show();
$('#player_listing').append('<%= j render("player") %>');

app/views/users/current_users.js.erb
$('#append_me').html("<%= j render('current_users') %>");

app/views/users/destroy.js.erb
$('#<%= user_id_helper(@user) %>').remove();

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, User.STATUSES, {}, { :prompt => 'Select Place' } %>
  </div>
  <div class="actions">
    <%= f.submit "Save changes", :class => "btn btn-large" %>
  </div>
<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.name, user %></td>
    <% if can? [:update, :destroy], user %>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if can? :create, @user %>
<%= link_to 'New User', new_user_path %>
<% end %>

app/views/users/mark_interested_gear.js.erb
$('#interested_or_not').html("<%= j render('uninterested') %>");

app/views/users/mark_uninterested_gear.js.erb
$('#interested_or_not').html("<%= j render('interested') %>");

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/new.js.erb
$('#tournies_link').hide();
$('#players_link').hide();
$('#gear_link').hide();
$('#new_player_link').hide().after('<%= j render("form") %>');

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<p>
  <b>Status:</b>
  <%= @user.status %>
</p>
<% if can? :read, Gear.new %>
<div class="dropdown">  
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= @user.name %>'s Gear Interests<b class="caret"></b></a>  
                        <ul class="dropdown-menu">
                          <% @user.users_gears.each do |ug| %> 
                            <li><%= link_to "#{User.find(Gear.find(ug.gear_id).user_id).name}'s #{Gear.find(ug.gear_id).name}",  Gear.find(ug.gear_id) %></li>  
                          <% end %>  
                        </ul>  
                    </div>
                    <br >
  <% if current_user.id == @user.id %>
  <div class="accordion" id="accordion2">
     <!--<div class="accordion-heading btn">-->
      <a class="accordion-toggle btn" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        Anyone Interested in My Stuff?
      </a>
    <!--</div>-->
    <div id="collapseOne" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul>
          <% @user.gears.each do |gear| %>
            <% UsersGear.all.each do |ug| %>
            <% if gear.id == ug.gear_id %>
            <li><%= User.find(ug.user_id).name %>'s interested in your <%= gear.name %></li>
            <% end %>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  </div>
  <% end %>
  <p>
  <b>Owned Gear:</b>
  </p>
  <div id="gear_listing">
    <% @user.gears.each do |gear| %>
      <p id="<%= gear_id_helper(gear) %>"><%= link_to gear.name, gear %>  <% if can? :destroy, gear %> <%= link_to 'Destroy gear', user_gear_path(@user, gear), confirm: "Are you sure?", method: :delete, remote: true %><% end %></p>
    <% end %>
  </div>
  <% if can? :create, Gear.new(:user_id => @user.id) %>
  <%= link_to 'Add Gear', new_user_gear_path(@user), id: "new_user_gear_link", remote: true %> |
  <% end %>
  <% end %>



<% if can? :update, @user %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<% end %>
<%= link_to 'Back Home', root_path %>