config/routes.rb
Paintball::Application.routes.draw do

  get "static_pages/home"

  get "static_pages/contact"

  get "static_pages/about"

  get "static_pages/tournaments"

  get "static_pages/current_roster"

  get "static_pages/users"

  get "static_pages/gears"

  resources :tournaments do
    resources :participants
    resources :results
  end

  resources :users do
    get "mark_interested_gear", on: :member #member means you have to give it a user's id
    get "mark_uninterested_gear", on: :member
    resources :gears
  end
  resources :users

  root to: 'static_pages#home'

  resources :tournaments

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :gears, only: [:index, :show]

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  attr_accessible :date, :location
  has_many :participants, dependent: :destroy
  has_many :results, dependent: :destroy

  validates :date, presence: true
  validates :location, presence: true
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  load_and_authorize_resource
  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tournaments }
    end
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
    @tournament = Tournament.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tournament }
    end
  end

  # GET /tournaments/new
  # GET /tournaments/new.json
  def new
    @tournament = Tournament.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tournament }
      format.js
    end
  end

  # GET /tournaments/1/edit
  def edit
    @tournament = Tournament.find(params[:id])
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(params[:tournament])

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render json: @tournament, status: :created, location: @tournament }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tournaments/1
  # PUT /tournaments/1.json
  def update
    @tournament = Tournament.find(params[:id])

    respond_to do |format|
      if @tournament.update_attributes(params[:tournament])
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament = Tournament.find(params[:id])
    @tournament.destroy

    respond_to do |format|
      format.html { redirect_to tournaments_url }
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
	def tournament_id_helper(tournament)
		"tournament_#{tournament.id}"
	end
end

app/views/tournaments/_form.html.erb
<div id="new_tournament">
<%= form_for(@tournament) do |f| %>
  <% if @tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% @tournament.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date,
    { :default => {:year => 2008, 
           :month => 11, 
                    :day => 4},
       :use_short_month=>true 
    },
     :class=>'date_select' %>

  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/tournaments/_tournament.html.erb
 <tr id="<%= tournament_id_helper(@tournament) %>">
    <td><%= @tournament.date %></td>
    <td><%= @tournament.location %></td>
    <td><%= link_to 'View Tournament', @tournament %></td>
    <td><%= link_to 'Destroy', @tournament, confirm: 'Are you sure?', method: :delete %></td>
  </tr>

app/views/tournaments/create.js.erb
$('#new_tournament').remove();
$('#new_tournament_link').show();
$('#tournies_link').show();
$('#players_link').show();
$('#gear_link').show();
$('#tournament_listing').append('<%= j render(@tournament) %>');

app/views/tournaments/destroy.js.erb
$('#<%= tournament_id_helper(@tournament) %>').remove();

app/views/tournaments/edit.html.erb
<h1>Editing tournament</h1>

<%= render 'form' %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/index.html.erb
<h1>Listing tournaments</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tournaments.each do |tournament| %>
  <tr>
    <td><%= tournament.date %></td>
    <td><%= tournament.location %></td>
    <td><%= link_to 'View Tournament', tournament %></td>
    <% if can? [:destroy, :update], @tournament %>
    <td><%= link_to 'Destroy', tournament, confirm: 'Are you sure?', method: :delete %></td>
    <% end %>
    
    
  </tr>
<% end %>
</table>

<br />
<% if can? :create, @tournament %>
<%= link_to 'New Tournament', new_tournament_path, id: "new_tournament_link", remote: true %>
<% end %>

app/views/tournaments/new.html.erb
<h1>New tournament</h1>

<%= render 'form' %>

<%= link_to 'Back', tournaments_path %>

app/views/tournaments/new.js.erb
$('#new_tournament_link').hide().after('<%= j render("form") %>');

app/views/tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @tournament.date %>
</p>

<p>
  <b>Location:</b>
  <%= @tournament.location %>
</p>

<div>
	<p><b>SMU Participants</b></p>
	<ul id="participant_listing">
	  <% @tournament.participants.each do |participant| %>
	  <li id="<%= participant_id_helper(participant) %>"><%= User.find(participant.user_id).name %>   <% if can? :destroy, @participant %><%= link_to 'delete participant', tournament_participant_path(@tournament, participant), confirm: "Are you sure?", method: :delete, remote: true %><% end %></li>
	  <% end %>
    </ul>
    
</div>

<br />
<% if can? :create, @particiant %>
<%= link_to 'Add Participants', new_tournament_participant_path(@tournament), id: "new_tournament_participant_link", remote: true %>
<% end %>

<br >

<table class="table table-bordered" id="result_listing">
  <tr>
    <th>Place</th>
    <th>Team Name</th>
  </tr>

<% @tournament.results.each do |result| %>
  <tr id="<%= result_id_helper(result) %>">
    <td><%= result.place %></td>
    <td><%= result.team_name %>   <% if can? :destroy, @result %><%= link_to 'delete result', tournament_result_path(@tournament, result), method: :delete, remote: true %> <% end %></td>
  </tr>
<% end %>
</table>
<% if can? :create, @result %>
<%= link_to 'Add Results', new_tournament_result_path(@tournament), id: "new_tournament_result_link", remote: true %>
<% end %>
<br />



<div class="footer">
<% if can? :update, Tournament %>
<%= link_to 'Edit', edit_tournament_path(@tournament) %> |
<% end %>
<%= link_to 'Back Home', root_path %>
</div>