config/routes.rb
Paintball::Application.routes.draw do

  get "static_pages/home"

  get "static_pages/contact"

  get "static_pages/about"

  get "static_pages/tournaments"

  get "static_pages/current_roster"

  get "static_pages/users"

  get "static_pages/gears"

  resources :tournaments do
    resources :participants
    resources :results
  end

  resources :users do
    get "mark_interested_gear", on: :member #member means you have to give it a user's id
    get "mark_uninterested_gear", on: :member
    resources :gears
  end
  resources :users

  root to: 'static_pages#home'

  resources :tournaments

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :gears, only: [:index, :show]

end

app/models/gear.rb
class Gear < ActiveRecord::Base
  attr_accessible :cost, :description, :for_sale, :name, :user_id
  belongs_to :user
  has_many :users_gears, dependent: :destroy
  

  validates :name, presence: true
  validates :user_id, presence: true

  def self.selling(for_sale = true)
  	where("for_sale == ? ", for_sale)
  end
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  load_and_authorize_resource
  # GET /gears
  # GET /gears.json
  def index
    @gears = Gear.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gears }
    end
  end

  # GET /gears/1
  # GET /gears/1.json
  def show
    @gear = Gear.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gear }
    end
  end

  # GET /gears/new
  # GET /gears/new.json
  def new
    @gear = Gear.new
    @user = User.find(params[:user_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gear }
      format.js # new.js.erb
    end
  end

  # GET /gears/1/edit
  def edit
    @gear = Gear.find(params[:id])
  end

  # POST /gears
  # POST /gears.json
  def create
    @gear = Gear.new(params[:gear])
    @user = User.find(params[:user_id])
    @gear.user_id = @user.id

    respond_to do |format|
      if @gear.save
        format.html { redirect_to @user, notice: 'Gear was successfully created.' }
        format.json { render json: @gear, status: :created, location: @gear }
        format.js #create.js.erb
      else
        format.html { render action: "new" }
        format.json { render json: @gear.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gears/1
  # PUT /gears/1.json
  def update
    @gear = Gear.find(params[:id])

    respond_to do |format|
      if @gear.update_attributes(params[:gear])
        format.html { redirect_to @gear, notice: 'Gear was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gears/1
  # DELETE /gears/1.json
  def destroy
    @gear = Gear.find(params[:id])
    @user = User.find(params[:user_id])
    @gear.destroy
    

    respond_to do |format|
      format.html { redirect_to @user }
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/gears_helper.rb
module GearsHelper
	def gear_id_helper(gear)
		"gear_#{gear.id}"
	end
	
end

app/views/gears/_form.html.erb
<div id="new_gear">
<%= form_for([@user, @gear], remote: true) do |f| %>
  <% if @gear.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gear.errors.count, "error") %> prohibited this gear from being saved:</h2>

      <ul>
      <% @gear.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :for_sale %><br />
    <%= f.check_box :for_sale %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/gears/_gear.html.erb
<p id='<%= gear_id_helper(@gear) %>'><%= link_to @gear.name, @gear %>  <%= link_to 'Destroy gear', user_gear_path(@user, @gear), confirm: "Are you sure?", method: :delete, remote: true %></p>

app/views/gears/_interested.html.erb
<%= form_for current_user, :method => :put do |f| %>
	<% current_user.interested(@gear) %>

	<%= f.submit "Mark Interested", :class => "btn btn-large btn-primary" %>
<% end %>

app/views/gears/create.js.erb
$('#new_gear').remove();
$('#new_user_gear_link').show();
$('#gear_listing').append('<%= j render(@gear) %>');

app/views/gears/destroy.js.erb
$('#<%= gear_id_helper(@gear) %>').remove();

app/views/gears/edit.html.erb
<h1>Editing gear</h1>

<%= render 'form' %>

<%= link_to 'Show', @gear %> |
<%= link_to 'Back', gears_path %>

app/views/gears/index.html.erb
<h1>Listing All Gear</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Owner</th>
    <th>For Sale</th>
    <th>Cost</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% User.all.each do |user| %>
<% user.gears.each do |gear| %>
  <tr id="<%= gear_id_helper(gear) %>">
    <td><%= link_to gear.name, gear %></td>
    <td><%= user.name %></td>
    <% if gear.for_sale %>
    <td>Yes</td>
    <td>$<%= gear.cost %></td>
    <% else %>
    <td>No</td>
    <td>N/A</td>
    <% end %>
    <% if can? :destroy, gear %>
    <td><%= link_to 'Destroy', user_gear_path(user, gear), confirm: 'Are you sure?', method: :delete, remote: true %></td>
    <% end %>
  </tr>
<% end %>
<% end %>
</table>

app/views/gears/new.html.erb
<h1>New gear for <%= @user.name %></h1>

<%= render 'form' %>

<%= link_to 'Back to profile', @user %>

app/views/gears/new.js.erb
$('#new_user_gear_link').hide().after('<%= j render("form") %>');

app/views/gears/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Owner:</b>
  <%= User.find(@gear.user_id).name %>
</p>

<p>
  <b>Cost:</b>
  $<%= @gear.cost %>
</p>

<p>
  <b>Name:</b>
  <%= @gear.name %>
</p>

<p>
  <b>Description:</b>
  <%= @gear.description %>
</p>

<p>
  <b>For sale:</b>
  <% if @gear.for_sale %>
  Yes
  <br >
<% unless current_user.id == @gear.user_id %>
<div id="interested_or_not">
  <% if current_user.is_interested(@gear) %>
  <p id="already_interested">You're already interested</p><br >
  <%= link_to "Not Interested Anymore", mark_uninterested_gear_user_path(current_user, gear_id: @gear.id), :class => "btn btn-large btn-danger", remote: true %>
  <% else %>
  <p id="interested">Interested in this piece of gear?</p><br >
 <%= link_to "Mark Interested", mark_interested_gear_user_path(current_user, gear_id: @gear.id), :class => "btn btn-large btn-primary", remote: true %>
  <% end %>
</div>
<% end %>

  <% else %>
  No
  <% end %>
</p>



<br >

<%= link_to "Back Home", root_path %> |
<%= link_to "Owner's Profile", user_path(@gear.user_id) %>